create table users(
    id integer generated by default as identity primary key,
    email         varchar(50) not null unique,
    password      varchar     not null,
    name          varchar     not null,
    surname       varchar     not null,
    father_name   varchar,
    date_of_birth date,
    phone_number  varchar,
    photo_path    varchar,
    role          varchar not null
);
create  table auth_info(
    user_id int primary key references users(id) on delete cascade,
    auth_time timestamp
);