create table users(
    id integer generated by default as identity primary key,
    email         varchar(50) not null unique,
    password      varchar     not null,
    name          varchar     not null,
    surname       varchar     not null,
    father_name   varchar,
    date_of_birth date,
    phone_number  varchar,
    role          varchar not null
);
